# Generated by Django 5.2.5 on 2025-10-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mealplans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(help_text='e.g., 2 lbs, 1 cup', max_length=50)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat & Seafood'), ('dairy', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=20)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False, help_text='Mark as priority item')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shopping List Item',
                'verbose_name_plural': 'Shopping List Items',
                'ordering': ['is_purchased', 'category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(blank=True, help_text='Optional: Link to meal plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='mealplans.mealplan')),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'ordering': ['-created_at'],
            },
        ),
    ]
