# Generated by Django 5.2.5 on 2025-11-13 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users this shopping list is shared with', related_name='shared_shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
