# Generated by Django 5.2.5 on 2025-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, help_text='Recipe video (MP4, WebM, or OGG format recommended)', null=True, upload_to='recipes/videos/'),
        ),
    ]
