# Generated by Django 5.2.5 on 2025-11-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, help_text="Recipe author's reply to the review"),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
