# Generated by Django 5.2.5 on 2025-10-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mealplans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplans.mealplan'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', '-start_date'], name='mealplans_m_user_id_01d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['meal_plan', 'date'], name='mealplans_m_meal_pl_a56895_idx'),
        ),
    ]
